config/routes.rb
LlcJobboard::Application.routes.draw do
  devise_for :admins, :path => 'admin', :path_names => { sign_in: '' }
  devise_for :users

  root 'job_posts#index'

  resources :job_posts do
    collection do
      get 'user_posts'
    end

    member do
      post 'charge'
    end
  end

  resources :job_applications, only: [:create, :show, :index]

  get 'style' => 'pages#style_guide'

  get 'tags/:tag', to: 'job_posts#index', as: :tag

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'new' => 'dashboard#new_admin'
    post 'create' => 'dashboard#create_admin'

    resources :categories
    resources :job_types

    resources :job_posts do
      member do
        put 'activate'
        put 'reject'
        put 'hide_or_show'
      end
    end
  end
end

app/controllers/admin/job_types_controller.rb
class Admin::JobTypesController < ApplicationController
  def index
    @job_types = JobType.all
    @job_type = JobType.new
  end

  def create
    @job_type = JobType.new(job_type_params)

    if @job_type.save
      redirect_to :admin_job_types
    else
      render 'new'
    end
  end

  def destroy
    @job_type = JobType.find(params[:id])
    if @job_type.job_posts.empty?
      @job_type.destroy
      redirect_to :admin_job_types
    else
      redirect_to :admin_job_types, alert: "It has job posts"
    end
  end

  private
  def job_type_params
    params.require(:job_type).permit(:name)
  end
end

app/helpers/admin/job_types_helper.rb
module Admin::JobTypesHelper
end

app/views/admin/job_types/index.html.erb
<%= simple_form_for(@job_type, url: admin_job_types_path, method: :post ) do |f| %>
<%= f.input :name, input_html: { class: 'form-control' } %>
<div class="form-group">
    <div>
        <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
</div>
<% end %>

<div class="list-group">
    <% @job_types.each do |job_type| %>
      <li><%= job_type.name %> | <%= link_to 'Destroy', admin_job_type_path(job_type), method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
</div>