config/routes.rb
LlcJobboard::Application.routes.draw do
  devise_for :admins, :path => 'admin', :path_names => { sign_in: '' }
  devise_for :users

  root 'job_posts#index'

  resources :job_posts do
    collection do
      get 'user_posts'
    end

    member do
      post 'charge'
    end
  end

  resources :job_applications, only: [:create, :show, :index]

  get 'style' => 'pages#style_guide'

  get 'tags/:tag', to: 'job_posts#index', as: :tag

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'new' => 'dashboard#new_admin'
    post 'create' => 'dashboard#create_admin'

    resources :categories
    resources :job_types

    resources :job_posts do
      member do
        put 'activate'
        put 'reject'
        put 'hide_or_show'
      end
    end
  end
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :category
  belongs_to :job_type
  belongs_to :user
  belongs_to :admin

  has_many :job_applications
  has_many :transactions

  acts_as_taggable

  default_scope { order(created_at: :desc) }

  scope :by_category, lambda { |category_id| where("category_id = ?", category_id) }
  scope :by_job_type, lambda { |job_type_id| where("job_type_id = ?", job_type_id) }
  scope :active, lambda { where("state = 'active'") }
  scope :expired, lambda { where("expires_at < ?", Time.now) }

  validates_presence_of :title, :description, :job_type_id, :category_id, :due_date, :city, :country, :company, :how_to_apply

  state_machine :initial => :not_approved do
    before_transition [:not_approved, :rejected, :expired] => :active, :do => [:set_expiry_date, :set_old_date]

    event :activate do
      transition [:not_approved, :rejected, :expired] => :active
    end

    event :reject do
      transition all => :rejected
    end

    event :expire do
      transition all => :expired
    end

    event :hide do
      transition :active => :hidden
    end

    event :show do
      transition :hidden => :active
    end
  end

  def charge(token, email)
    charge = Stripe::Charge.create(
      :amount => 3000,
      :currency => "cad",
      :card => token,
      :description => "#{email} paid for #{title}"
    )

    if charge["paid"] && !charge["failure_code"]
      transactions.create(stripe_response: charge)
      activate
      UserMailer.confirmation_email(email, self).deliver
    elsif charge["failure_message"]
      raise StandardError, "Credit card charge failed with this message: #{charge["failure_message"]}"
    end
  end

  def is_fresh?
    Time.now.to_date < old_at.to_date
  end

  def expires_in
    (expires_at.to_date - Time.now.to_date).to_i
  end

  def self.hide_expired
    JobPost.expired.each { |post| post.expire }
  end

  private
  def set_old_date
    update(old_at: 3.days.from_now)
  end

  def set_expiry_date
    update(expires_at: 30.days.from_now)
  end
end

app/controllers/admin/job_posts_controller.rb
class Admin::JobPostsController < Admin::AdminAreaController
  before_action :load_job_post, only: [:activate, :hide_or_show, :reject]

  def index
    @job_posts = JobPost.all
  end

  def reject
    @job_post.reject
    redirect_to :admin_job_posts
  end

  def activate
    @job_post.activate
    redirect_to :admin_job_posts
  end

  def hide_or_show
    if @job_post.hidden?
      @job_post.show
    elsif @job_post.active?
      @job_post.hide
    end
    redirect_to :admin_job_posts
  end

  def new
    @job_post = JobPost.new
    @categories = Category.all
    @job_types = JobType.all
  end

  def create
    @job_post = current_admin.job_posts.new(job_post_params)
    @categories = Category.all
    @job_types = JobType.all

    if @job_post.save
      @job_post.activate
      redirect_to @job_post
    else
      render 'new'
    end
  end

  private
  def load_job_post
    @job_post = JobPost.find(params[:id])
  end

  def job_post_params
    params.require(:job_post).permit(:title, :description, :how_to_apply, :company, :due_date, :tag_list, :category_id, :job_type_id, :city, :country)
  end
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_job_post, only: [:show, :charge]

  def index
    @categories = Category.all
    @job_types = JobType.all
    @job_posts = JobPost.active

    if params[:tag]
      @job_posts = @job_posts.tagged_with(params[:tag])
    elsif params[:category] || params[:job_type]
      @job_posts = @job_posts.by_category(params[:category]) if params[:category].present?
      @job_posts = @job_posts.by_job_type(params[:job_type]) if params[:job_type].present?
    end

    @job_posts = @job_posts.order('expires_at DESC').paginate(page: params[:page])
  end

  def user_posts
    @job_posts = current_user.job_posts.paginate(page: params[:page])
  end

  def new
    @job_post = JobPost.new
    @categories = Category.all
    @job_types = JobType.all
  end

  def create
    @job_post = current_user.job_posts.new(job_post_params)
    @categories = Category.all
    @job_types = JobType.all

    if @job_post.save
      redirect_to @job_post, :alert => "Your post is not published yet. Click Publish to continue."
    else
      render 'new'
    end
  end

  def show
    @job_application = @job_post.job_applications.new
    raise ActionController::RoutingError.new('Not Found') if !@job_post.active? && @job_post.user_id != current_user.try(:id)
  end

  def charge
    @job_post.charge(params[:stripeToken], params[:stripeEmail])

    redirect_to @job_post, :notice => "Thank you for your payment!"
  rescue => e
    redirect_to @job_post, :alert => e.message
  end

  private
  def job_post_params
    params.require(:job_post).permit(:title, :description, :how_to_apply, :company, :due_date, :tag_list, :category_id, :job_type_id, :city, :country)
  end

  def token_params
    params.require(:token).permit(:id, :name)
  end

  def set_job_post
    @job_post = JobPost.find(params[:id])
  end
end

app/helpers/admin/job_posts_helper.rb
module Admin::JobPostsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
  def expiry_info(job_post)
    if job_post.expires_in > 0
      "Active for another #{pluralize(job_post.expires_in, "day")}"
    else
      "Will expire today"
    end
  end
end

app/views/job_posts/index.html.erb
<ul class="nav nav-pills">
  <% @job_types.each do |job_type| %>
    <li><%= link_to job_type.name, url_for(params.merge(:job_type => job_type.id)) %></li>
  <% end %>
</ul>

<div class="list-group job-posts">
    <% @job_posts.each do |job_post| %>
        <%= link_to job_post, :class => 'list-group-item' do %>
            <div class="job-post-heading">
                <h4 class="job-post-title"><%= job_post.title %></h4>
                <span class="job-post-type"><%= job_post.job_type.name %></span>
                <% if job_post.is_fresh? %>
                    <span class="label label-primary">NEW</span>
                <% end %>
            </div>
            <p class="list-group-item-text">
                <span class="job-post-company"><%= job_post.company %></span>
                <span class="job-post-location"><%= "(#{job_post.city}, #{job_post.country})" %></span>
            </p>
        <% end %>
    <% end %>
    <%= will_paginate %>
</div>

app/views/job_posts/new.html.erb
<%= simple_form_for(@job_post) do |f| %>
<%= f.input :title, input_html: { class: 'form-control' } %>
<%= f.input :company, input_html: { class: 'form-control' } %>
<div class="help-block">
    <p>Feel free to use markdown in the description and how to apply. Here are the basics. See the <a href="http://daringfireball.net/projects/markdown/syntax">complete syntax.</a></p>
    <ul>
        <li>Heading: ##Example heading</li>
        <li>List item: *Example list item</li>
        <li>Italic text: _Example italic text_</li>
        <li>Bold text: __Example bold text__</li>
        <li>Link: [Example link](http://example.com)</li>
    </ul>
</div>
<%= f.input :description, input_html: { class: 'form-control' } %>
<%= f.input :how_to_apply, input_html: { class: 'form-control' } %>
<%= f.input :due_date, input_html: { class: 'form-control date-fragment' } %>
<%= f.input :category_id, as: :select, collection: @categories, input_html: { class: 'form-control date-fragment' }  %>
<%= f.input :job_type_id, as: :select, collection: @job_types, input_html: { class: 'form-control date-fragment' }  %>
<%= f.input :tag_list, label: "Tags (separated by commas) - Some examples: html, rails, css3", input_html: { class: 'form-control' } %>
<%= f.input :city, input_html: { class: 'form-control' } %>
<%= f.country_select :country, ['Canada', 'United States'], {}, class: 'form-group form-control date-fragment' %>

<br>

<div class="form-group">
    <%= f.button :submit, class: 'btn btn-primary' %>
</div>
<% end %>

app/views/job_posts/show.html.erb
<% if admin_signed_in? %>
    <% if @job_post.not_approved? %>
        <%= link_to('Approve', activate_admin_job_post_url(@job_post), method: :put, class: "btn btn-primary") %>
        <%= link_to('Reject', reject_admin_job_post_url(@job_post), method: :put, class: "btn btn-danger") %>
    <% elsif @job_post.active? %>
        <%= link_to('Hide', hide_or_show_admin_job_post_url(@job_post), method: :put, class: "btn btn-danger") %>
    <% elsif @job_post.hidden? %>
        <%= link_to('Show', hide_or_show_admin_job_post_url(@job_post), method: :put, class: "btn btn-primary") %>
    <% elsif @job_post.rejected? %>
        <%= link_to('Approve', activate_admin_job_post_url(@job_post), method: :put, class: "btn btn-primary") %>
    <% end %>
<% end %>

<% if !@job_post.active? and current_user %>

<button id="publish-button" class="btn btn-primary">Publish</button>

<%= form_tag(charge_job_post_path(@job_post), :id => 'stripeForm') do %>
<%= hidden_field_tag :stripeToken %>
<%= hidden_field_tag :stripeEmail %>
<% end %>
<% end %>

<h1><%= @job_post.title %></h1>

<h3><%= @job_post.company %></h3>

<div class="post-description"><%= auto_link(BlueCloth.new(@job_post.description).to_html).html_safe %></div>

<% if @job_post.tag_list.present? %>
  <p>Tags: <%= raw @job_post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
<% end %>

<div class="well">
    <h3>How to apply:</h3>
    <div class="post-description"><%= auto_link(BlueCloth.new(@job_post.how_to_apply).to_html).html_safe %></div>
</div>

<% if !@job_post.active? and current_user %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script type="text/javascript">
    $(function() {
      var handler = StripeCheckout.configure({
        key: '<%= ENV["stripe_public_token"] %>',
        // image: '/square-image.png',
        token: function(token, args) {
          document.getElementById("stripeToken").value = token.id;
          document.getElementById("stripeEmail").value = token.email;
          document.getElementById("stripeForm").submit();
        }
      });

      document.getElementById('publish-button').addEventListener('click', function(e) {
        // Open Checkout with further options
        handler.open({
          name: 'Ladies Learning Code',
          description: 'Job Post for 30 days ($30.00)',
          amount: 3000,
          currency: 'CAD',
          email: "<%= current_user.email %>"
        });
        e.preventDefault();
      });
    });
  </script>
<% end %>

app/views/job_posts/user_posts.html.erb
<div class="list-group job-posts">
    <% @job_posts.each do |job_post| %>
      <ul class="list-group">
        <li class="list-group-item">
        <% if job_post.rejected? %>
          <h2 class="list-group-item-heading"><strike><%= job_post.title %></strike></h2>
        <% else %>
          <h2 class="list-group-item-heading"><%= link_to job_post.title, job_post %></h2>
        <% end %>

        <% if job_post.active? %>
          <span title="<%= job_post.expires_at.strftime("%a, %B %d %Y") %>" ><%= expiry_info(job_post) %></span>
        <% else %>
          <h4><span class="label label-warning">HIDDEN</span></h4>
        <% end %>
        </li>
      </ul>
    <% end %>
    <%= will_paginate %>
</div>