config/routes.rb
LlcJobboard::Application.routes.draw do
  devise_for :admins, :path => 'admin', :path_names => { sign_in: '' }
  devise_for :users

  root 'job_posts#index'

  resources :job_posts do
    collection do
      get 'user_posts'
    end

    member do
      post 'charge'
    end
  end

  resources :job_applications, only: [:create, :show, :index]

  get 'style' => 'pages#style_guide'

  get 'tags/:tag', to: 'job_posts#index', as: :tag

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'new' => 'dashboard#new_admin'
    post 'create' => 'dashboard#create_admin'

    resources :categories
    resources :job_types

    resources :job_posts do
      member do
        put 'activate'
        put 'reject'
        put 'hide_or_show'
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <p>© <%= Time.now.year %> <%= link_to("Ladies Learning Code", "http://ladieslearningcode.com/") %></p>
            <p>Built by <%= link_to("Berk Caputcu", "https://twitter.com/bcaputcu") %>,
                <%= link_to("Philip Karpiak", "https://twitter.com/eswat") %> and
                <%= link_to("Thomas Martineau", "https://twitter.com/TMartineau") %>
            </p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
        <div class="row">
            <a class="col-md-5" href="/"><%= image_tag("llc-jobs-logo.png", class: "logo-llc img-responsive", alt: "Ladies Learning Code") %></a>
            <nav class="col-md-7">
                <ul class="nav nav-pills <%= job_show? ? 'hidden-xs' : '' %>">
                    <li><a href="/">All Jobs</a></li>
                    <li><a href="/job_posts/new">Post a Job</a></li>
                    <% if admin_signed_in? %>
                        <li><a href="/admin/dashboard">Dashboard</a></li>
                        <li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
                    <% else %>
                        <% if user_signed_in? %>
                            <li><%= link_to('My Posts', user_posts_job_posts_path) %></li>
                            <li><%= link_to('Account', edit_user_registration_path) %></li>
                            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                        <% else %>
                            <li><%= link_to('Sign in', new_user_session_path) %></li>
                        <% end %>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LLC - Job Board</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Quicksand:700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container">
    <% if job_posts? %>
      <ul class="job-categories nav nav-tabs nav-justified">
        <li><a href="/">All Jobs</a></li>
        <% @categories.each do |category| %>
          <li><%= link_to category.name, url_for(params.merge(:category => category.id)) %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="<%= content_col_class %>">
        <% if admin_area? %>
          <ul class="nav nav-tabs admin-nav">
            <li><%= link_to 'Dashboard', :admin_dashboard %></li>
            <li><%= link_to 'Job Posts', :admin_job_posts %></li>
            <li><%= link_to 'Categories', :admin_categories %></li>
            <li><%= link_to 'Job Types', :admin_job_types %></li>
          </ul>
        <% end %>
        <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
    <% unless admin_area? %>
      <aside class="sidebar col-sm-3">
          <div class="well post-a-job">
            <h4><strong>$30</strong> for <strong>30</strong> days</h3>
            <p>All proceeds support Ladies Learning Code.</p>
            <a href="/job_posts/new" class="btn btn-primary btn-lg" role="button">Post a Job</a>
          </div>
          <small>
            Ladies Learning Code Jobs is a place for you to find the talent you need or the job you want, while supporting a not-for-profit organization.
          </small>
          <div id="tag_cloud">
            <h3>Tags</h3>
            <% tag_cloud JobPost.active.tag_counts, %w{s m l} do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div>
      </aside>
    <% end %>

</div>

<%= render "layouts/footer" %>

</body>
</html>